version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/gitlab/config:/etc/gitlab"
      - "$PWD/gitlab/data:/var/opt/gitlab"
      - "$PWD/gitlab/log:/var/log/gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://example.com"
  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: "gitlab-runner"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/gitlab-runner:/etc/gitlab-runner"
