version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "$PWD/conf.d:/etc/nginx/conf.d:ro"
      - "$PWD/html:/usr/share/nginx/html:ro"
      - "$PWD/live:/etc/letsencrypt/live/:ro"
